✨ Allow up to 2% slippage in the AMM
Hyle-org/hyle pull request #420
Opened 2024-12-09 14:11 UTC by wraitii

2024-12-09 17:10 UTC, maxgttph commented on contracts/amm/contract/src/lib.rs
> +            let k = *prev_y - (*prev_x * *prev_y / (*prev_x + from_amount));
Le nom de variable k est confusante:  la formule de swap d'AMM est souvent écrite `k=x*y`

2024-12-09 17:10 UTC, maxgttph commented on contracts/amm/contract/src/lib.rs
> +        if to_amount < expected_to_amount * 100 / 102 {
J'aurais fait comme ça 
```suggestion
        if to_amount < expected_to_amount * 98 / 100 {
```
je dis n'imp ? :thinking:

2024-12-09 17:51 UTC, wraitii commented on contracts/amm/contract/src/lib.rs
> +        if to_amount < expected_to_amount * 100 / 102 {
Ça doit jouer sur les arrondis mais pas sûr que ça change tant de choses en pratique

2024-12-10 10:29 UTC, maxgttph commented on contracts/amm/contract/src/lib.rs
> +        if to_amount < expected_to_amount * 100 / 102 {
On est pas sur un slippage à 2% mais 1.96% si je me trompe pas
Mais osef aha

2024-12-10 10:34 UTC, BertrandD approved these changes

2024-12-10 10:37 UTC, maxgttph requested changes

2024-12-10 10:37 UTC, maxgttph commented on contracts/amm/contract/src/lib.rs
> -                    if amount_b != to_amount {
Hum on dirait que le seul check qu'on fait maintenant c'est de s'assurer que le User s'envoit suffisamment de token. Mais jamais on vérifie qu'il n'en envoit pas trop
J'ai l'impression qu'il n'y a pas de check pour l'empecher de vider la pool

2024-12-10 10:58 UTC, wraitii commented on contracts/amm/contract/src/lib.rs
> -                    if amount_b != to_amount {
Je vois pas en quoi on faisait ce check avant à vrai dire ?

2024-12-10 11:21 UTC, maxgttph commented on contracts/amm/contract/src/lib.rs
> -                    if amount_b != to_amount {
On faisait `if amount_b != to_amount {`
qui garantissait l'exact égalité entre ce qui a été calculé comme nouvelle valeur et ce qui a été envoyé
Mais avec ça y'avait pas de slippage autorisé

2024-12-10 11:25 UTC, maxgttph commented on contracts/amm/contract/src/lib.rs
> +        if to_amount < expected_to_amount * 100 / 102 {
je pense qu'un fix possible serait d'encadrer to_amount 
```suggestion
        let epsilon = 2/100;
        if  expected_to_amount * (1-epsilon) < to_amount && to_amount < expected_to_amount (1+epsilon) {
```

Par contre je suis pas certain qu'il n'y ait pas un scénario où la valeur de k diminue lentement si l'arrondi se fait "dans le mauvais sens"

2024-12-10 11:50 UTC, wraitii commented on contracts/amm/contract/src/lib.rs
> -                    if amount_b != to_amount {
Je dis peut-être nawal mais je fais déjà l'encadrement non ?

2024-12-10 14:05 UTC, merged