propagate consensus proposal hash in indexer
Hyle-org/hyle pull request #481
Opened 2024-12-20 14:31 UTC by hhalex

2024-12-23 09:11 UTC, BertrandD requested changes

2024-12-23 09:11 UTC, BertrandD commented on src/consensus.rs
> +    ) -> SignedBlock {
imho this function should be in genesis.rs

2024-12-23 09:11 UTC, BertrandD commented on src/data_availability.rs
> +                warn!(
I don't think this should be warn. A new node cathing up will log a warn for each block, this is a "normal" case when catching up

2024-12-23 09:11 UTC, BertrandD commented on src/indexer/migrations/20241009154948_create_tables.sql
> +    hash BYTEA PRIMARY KEY,          -- Corresponds to BlockHash
when doing debug, having a TEXT field is very much easier to query than a BYTEA, I highly recommend to keep a string there

2024-12-30 13:17 UTC, wraitii commented on src/consensus.rs
> +    ) -> SignedBlock {
Found the answer -> we need the consensus proposal or we won't be able to get the hash.
I work around it in my version of this diff

2024-12-31 09:26 UTC, wraitii commented
Done in #504

2024-12-31 09:26 UTC, closed without merging

2025-01-06 14:07 UTC, hhalex commented on src/indexer/migrations/20241009154948_create_tables.sql
> +    hash BYTEA PRIMARY KEY,          -- Corresponds to BlockHash
Not sure I agree... You can encode/decode it with `encode(column, "hex")` when doing debug