WIP
Hyle-org/hyle pull request #90
Opened 2024-09-12 14:42 UTC by maxgttph

2024-09-12 14:47 UTC, BertrandD commented on src/node_state.rs
> +        match &blob_metadata.verifications_status.first().unwrap() {
attention à ne pas garder le unwrap() dans la version finale

2024-09-12 14:47 UTC, BertrandD commented on src/node_state.rs
> +            .map(|blob| match &blob.verifications_status.first().unwrap() {
same, :warning: unwrap()

2024-09-12 14:49 UTC, BertrandD commented on src/node_state.rs
> +                                    .unwrap()
:warning:

2024-09-16 07:42 UTC, hhalex commented on src/node_state.rs
> +        blobs_metadata
Peut-être un truc du genre `blobs.iter().any(|hyleoutput| !hyleoutput.success)` ?

2024-09-16 07:46 UTC, hhalex commented on src/node_state.rs
> +        let cloned_self = self.clone();
Pourquoi clone self?

2024-09-16 07:51 UTC, hhalex commented on src/node_state.rs
> +            .with_context(|| format!("Contract {} not found when settling", contract_name,))?;
`.with_context` est lazy comparé à `context()`, ça évite de calculer un message d'erreur inutilement. Ici tu évites une concaténation

2024-09-16 08:56 UTC, BertrandD commented on tests/e2e_test.rs
> +#[ignore]
why ?

2024-09-16 09:33 UTC, wraitii requested changes
Je request change parce que je suggère un assez gros changement qui je pense améliorera la PR, mais on peut en débattre

2024-09-16 09:33 UTC, wraitii commented on src/node_state.rs
> +            .collect::<Vec<&UnsettledTransaction>>();
on peut pas juste itérer le hashset ? Je pense qu'on clone tout là

2024-09-16 09:33 UTC, wraitii commented on src/node_state.rs
> +                .is_next_unsettled_tx(&unsettled_tx.hash, &contract_name);
Pour moi on veut run ça bien avant, ça stoppera probablement une grosse partie des runs.

2024-09-16 09:33 UTC, wraitii commented on src/node_state.rs
> +        }
Je ferai pas dans cette ordre là.

Le seul truc qu'on pourra settle c'est les contrats dont la next_tx vient d'être modifiée, potentiellement. Ça c'est une condition assez facile à checker, et on peut ensuite aller vérifier pour chacune de ses TX s'il y a un autre blob sans preuve pour l'instant. 

A mon avis c'est plus rapide + plus simple

2024-09-16 13:53 UTC, wraitii commented on src/node_state.rs
> +                None => return false, // No contract found for this blob
Ça semble un peu buggy comme case à vrai dire, en particulier pour le moment, mais pas opposé à juste return false -> j'irai bien rajouter une trace

2024-09-16 13:54 UTC, wraitii approved these changes

2024-09-16 13:55 UTC, merged